name: mapbox_navigation
description: A Flutter project for San Pablo City Tourism Dept.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.0.2
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  location:
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
  dio: ^5.2.0+1
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  carousel_slider: ^4.2.1
  easy_debounce: ^2.0.3
  flutter_sliding_up_panel: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  flutter_mapbox_navigation: ^0.2.2
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  webview_flutter: ^4.2.2
  showcaseview: ^2.0.3
  material_floating_search_bar_2: ^0.5.0
  path_provider: ^2.1.1
  flutter_map_tile_caching: ^9.0.0-dev.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  connectivity_plus: ^5.0.2
  shimmer: ^2.0.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/mapbox.png"

flutter_native_splash:
  color: "#000000"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/config/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic