// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmLJm0HFN-fJF6aC20k4IXKuhOhmOhY28',
    appId: '1:648442716708:web:4b5433ad522d6fa5afeeb1',
    messagingSenderId: '648442716708',
    projectId: 'spctourismapp',
    authDomain: 'spctourismapp.firebaseapp.com',
    storageBucket: 'spctourismapp.appspot.com',
    measurementId: 'G-PZ42WK5JTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClDafnErLGMBeGfGvv_Kr9fZDnIV1W1n8',
    appId: '1:648442716708:android:edf4fa6d3a991a14afeeb1',
    messagingSenderId: '648442716708',
    projectId: 'spctourismapp',
    storageBucket: 'spctourismapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpaXXj8x7drvRnkeKNWJEzlnABlXIHcaM',
    appId: '1:648442716708:ios:7d6559b281146af4afeeb1',
    messagingSenderId: '648442716708',
    projectId: 'spctourismapp',
    storageBucket: 'spctourismapp.appspot.com',
    iosBundleId: 'com.example.mapboxNavigation',
  );
}
